version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:16
    steps:
      - checkout  # Pulls your repo code to the CircleCI environment
      - run:
          name: Install dependencies
          command: |
            npm install  # Install the dependencies, including Jest
      #- run:
       #   name: Ensure Jest is executable
        #  command: |
         #   chmod +x ./node_modules/.bin/jest  # Ensure the Jest binary has execute permissions
      #- run:
       #   name: Run Jest Testing
        #  command: |
         #   jest ../test/app.test.js
         
  sonarcloud:
      docker:
        - image: circleci/openjdk:11
      steps:
        - checkout
        - run:
            name: Download SonarQube Scanner
            command: |
              curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
              unzip sonar-scanner.zip -d $HOME
        - run:
            name: SonarQube Analysis
            command: |
              $HOME/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
                -Dsonar.projectKey=$SONAR_PROJECT_KEY \
                -Dsonar.organization=$SONAR_ORG \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.login=$SONAR_TOKEN
 

  newmantest:
    docker:
      - image: cimg/node:18.20.2
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run Newman tests
          command: |
            npm run test-api &
      - attach_workspace:
          at: ~/workspace

workflows:
  version: 2
  test:
    jobs:
      - run_tests
      - sonarqube
      - newmantest:
          requires:
            - sonarqube
